actors:
  ko:
    image_url: /images/actors/alice.png
    name: Ko Ohashi
    url: https://kouohhashi.qrunch.io/
  sho:
    image_url: /images/actors/bob.png
    name: SHO(EDGE OF SPIRIT)
    url:
author: Ko Ohashi
description: 野球が好きな奴が野球についてダラダラ喋るポッドキャストです。
description_long: 野球が好きな奴が野球についてダラダラ喋るポッドキャストです。リラックスして聴いて頂けると嬉しいです。野球ポッドキャストではゲストを募集してしています。野球が好きな方ならどなたでも大歓迎です。
email: kouohhashi@sotuu.network
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: sotuuN
itunes_podcast_url: http://baseball.shabelab.com/feed.xml
keywords: 野球,プロ野球,ベースボール,Baseball,MLB,NPB,巨人,阪神,中日,ヤクルト,広島,DeNA,ソフトバンク,西武,楽天,ロッテ,オリックス,日ハム
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 喋野球ポッドキャスト
url: http://baseball.shabelab.com/
